# Generated by Django 3.2.8 on 2021-10-31 14:48

from django.db import migrations, models
import django.db.models.deletion
import main.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordGuild',
            fields=[
                ('guild_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Guild ID')),
                ('setting_plugin_admin', models.BooleanField(verbose_name='Модераторство')),
                ('setting_plugin_rank', models.BooleanField(verbose_name='Система рангов')),
                ('setting_plugin_economy', models.BooleanField(verbose_name='Экономика')),
                ('setting_plugin_games', models.BooleanField(verbose_name='Игры')),
                ('setting_plugin_birthday', models.BooleanField(verbose_name='Дни Рождения')),
                ('setting_plugin_music', models.BooleanField(verbose_name='Музыка')),
                ('log_channel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Log channel')),
            ],
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='User ID')),
                ('tag', models.CharField(max_length=50, verbose_name='Tag')),
                ('avatar', models.CharField(max_length=100, verbose_name='Avatar')),
                ('public_flags', models.IntegerField()),
                ('flags', models.IntegerField()),
                ('locale', models.CharField(max_length=100)),
                ('mfa_enabled', models.BooleanField()),
                ('last_login', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            managers=[
                ('objects', main.managers.DiscordOAuthManager()),
            ],
        ),
        migrations.CreateModel(
            name='DiscordUserInGuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='User ID')),
                ('balance', models.IntegerField(default=100, verbose_name='Баланс')),
                ('exp', models.IntegerField(default=0, verbose_name='Опыт')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('xp_time_lock', models.FloatField(verbose_name='EXP_TIME_LOCK')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Время Дня Рождения')),
                ('bank', models.IntegerField(default=0, verbose_name='Банк')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.discordguild', verbose_name='Guild')),
            ],
            options={
                'unique_together': {('guild', 'user')},
            },
        ),
    ]
