# Generated by Django 3.2.8 on 2021-11-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_discorduser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='username',
            field=models.CharField(default='ck1999', max_length=50, verbose_name='Nickname'),
            preserve_default=False,
        ),
    ]
