# Generated by Django 3.2.8 on 2021-11-01 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_discorduser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='is_superuser',
        ),
    ]
