# Generated by Django 3.2.8 on 2021-11-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_discorduser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordguild',
            name='name',
            field=models.CharField(default='Test', max_length=50, verbose_name='Guild name'),
            preserve_default=False,
        ),
    ]
