# Generated by Django 3.2.8 on 2021-11-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_discordguild_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, verbose_name='Token')),
                ('log', models.CharField(max_length=100, verbose_name='Log channel')),
                ('cooldown_classic', models.IntegerField(verbose_name='Cooldown Classic')),
                ('cooldown_medium', models.IntegerField(verbose_name='Cooldown Medium')),
                ('cooldown_large', models.IntegerField(verbose_name='Cooldown Large')),
                ('cooldown_day', models.IntegerField(verbose_name='Cooldown Extra')),
                ('sleep', models.IntegerField(verbose_name='Sleep Time')),
            ],
        ),
    ]
