# Generated by Django 3.2.8 on 2021-11-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_botsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordguild',
            name='prefix',
            field=models.CharField(default='>', max_length=2, verbose_name='Префикс'),
            preserve_default=False,
        ),
    ]
