# Generated by Django 3.2.8 on 2021-11-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_discordguild_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('user', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='User ID')),
                ('reason', models.CharField(default='No reason', max_length=100, verbose_name='Reason')),
            ],
        ),
    ]
